image:
  name: cirrusci/flutter
stages:
- coverage
- release
- deploy


code_analyze:
  stage: coverage
  script:
    - flutter pub get
    - flutter format lib/ test/ --set-exit-if-changed
    - flutter analyze


build_web:
  image: cirrusci/flutter
  stage: coverage
  script:
    - flutter pub get
    - flutter build web --release --verbose --base-href
  artifacts:
    paths:
      - build/web/



pages:
  stage: deploy
  image: ruby:latest
  script:
    - mv build/web/ public/
  artifacts:
    paths:
      - public
  only:
    - main
